# security:
#     cors:
#         enabled: true
#         paths:
#             '^/':
#                 origin_regex: true
#                 allow_origin: ['*']
#                 allow_headers: ['*']
#                 allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#                 max_age: 3600
